# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  
  config.vm.box = "m202-ubuntu1404"
  config.vm.box_url = "http://127.0.0.1/~adam/m202-ubuntu1404.box"

  config.vm.provision "shell", path: "provisioners/setup.sh"

  config.vm.provider "virtualbox" do |vb|
    # Uncomment the next line to show VM window. User/pass = vagrant/vagrant
    vb.gui = true
  
    vb.name = "m202-ubuntu1404"
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--cpus", "1"]  
  end

  config.vm.provider "vmware_fusion" do |v|
    # Uncomment the next line to show VM window. User/pass = vagrant/vagrant
    v.gui = true

    v.vmx["displayname"] = "m202-ubuntu1404"
    v.vmx["memsize"] = "2048"
    v.vmx["numvcpus"] = "1"
  end

  config.vm.provider "vmware_workstation" do |v|
    # Uncomment the next line to show VM window. User/pass = vagrant/vagrant
    v.gui = true

    v.vmx["displayname"] = "m202-ubuntu1404"
    v.vmx["memsize"] = "2048"
    v.vmx["numvcpus"] = "1"
  end
  config.ssh.username = "m202"
end
